---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  labels:
    app: grafana-app
    group: devops
data:
  ADMIN-USER: "grafana"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  labels:
    app: grafana-app
    group: devops
data:
  ADMIN-PASSWORD: "Z3JhZmFuYTEyMw=="
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana-app
    group: devops
  annotations:
spec:
  type: ClusterIP
  selector:
    app: grafana-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  labels:
    app: grafana-app
    group: devops
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: grafana-app
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-app
        group: devops
      annotations:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: grafana
          image: "grafana:11.3.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          envFrom:
            - configMapRef:
                name: grafana
            - secretRef:
                name: grafana
  volumeClaimTemplates:
  - metadata:
      name: grafana-storage
      annotations:
        volume.alpha.kubernetes.io/storage-class: longhorn
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 12Gi
